### ISSUE TITLE
Human should not make damage if wrong number

### ISSUE THREAD

**Issue by Husterknupp** [tmachale/arena-avenger#1]
Current situation in the damage computation is that only the time is measured how long the user needs to enter any key.

But we want the program to check that the right key was entered. Please
- either promt for a new console entry as long as the right number was entered 
- or lose the current round if wrong number
- or find another cool strategy

**Comment by tmachale** [comment]
Leave a comment
Greenleaves?

**Comment by Husterknupp** [comment]
I like it :+1:

**Comment by tmachale** [comment]
i like u :dancer:
