### ISSUE TITLE
Make arena runnable from command line

### ISSUE THREAD

**Issue by Husterknupp** [tmachale/arena-avenger#4]
Currently the app only run from within Eclipse. That is nice for some but bad others. To learn more about the process and to have less frameworks, lets resign from using maven.

I want it runnable from command line
- only library is Prog1Tools.IOTools, download into ./lib 
- document which commands are required to compile the java code as well as to run the compiled classes

**Comment by Husterknupp** [comment]
@tmachale I cannot push to your repo. Please go to arena-avenger > settings (on the right) > Collaborators > and add me as such

Because this is what git says
`remote: Permission to tmachale/arena-avenger.git denied to husterknupp.`

**Comment by tmachale** [comment]
u mean resign from eclipse, right?

**Comment by Husterknupp** [comment]
run w/o eclipse would also be nice. But I meant maven. You can easily add libraries to arena-avenger with that. Or automate tedious build steps like automated code testing.

**Comment by Husterknupp** [comment]
find in the README how to compile/run the code

**Comment by tmachale** [comment]
Why close?
Am 28.09.2015 20:42 schrieb "Benjamin Schandera" notifications@github.com:

**Comment by Husterknupp** [comment]
@tmachale I commited some changes. I can compile and run the code from the command line. BOOM.

Why not close?
